spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_ID}
    password: ${DB_USER_PW}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: ${REDIS_HOST}
    port: 6379
    auth-num-valid-time: ${REDIS_AUTH_NUM_VALID_TIME}

jwt:
  claim: ${CLAIM}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_VALID_TIME}
