spring:
  profiles:
    default: local

  output:
    ansi:
      enabled: always

  mail:
    host: ${SMTP_HOST}
    port: 465
    username: ${SMTP_ID}
    password: ${SMTP_PW}
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  login:
    grant-type: ${KAKAO_LOGIN_GRANT_TYPE}
    redirect-url: ${KAKAO_LOGIN_REDIRECT_URL}
