spring:
  profiles:
    default: local

  output:
    ansi:
      enabled: always

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_ID}
    password: ${SMTP_PW}
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

  redis:
    host: ${REDIS_HOST}
    port: 6379
    auth-num-valid-time: ${REDIS_AUTH_NUM_VALID_TIME}

jwt:
  claim: ${CLAIM}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_VALID_TIME}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  login:
    grant-type: ${KAKAO_LOGIN_GRANT_TYPE}
    redirect-url: ${KAKAO_LOGIN_REDIRECT_URL}
