name: Merge Swagger Files

on:
  push:
    paths:
      - 'backend/src/main/resources/api/root.yaml'

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Swagger CLI
        run: npm install -g swagger-cli

      - name: Merge Swagger Files
        run: swagger-cli bundle backend/src/main/resources/api/root.yaml -o docs/output.yaml -r -t yaml

      - name: Commit and Push Merged Swagger
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/output.yaml
          git commit -m "Merged OAS files"
          git push
